/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      cartesian_elbow_example_controller:
        type: franka_example_controllers/CartesianElbowExampleController

      cartesian_orientation_example_controller:
        type: franka_example_controllers/CartesianOrientationExampleController

      cartesian_pose_elbow_example_controller:
        type: franka_example_controllers/CartesianElbowExampleController

      cartesian_pose_example_controller:
        type: franka_example_controllers/CartesianPoseExampleController

      cartesian_velocity_example_controller:
        type: franka_example_controllers/CartesianVelocityExampleController

      elbow_example_controller:
        type: franka_example_controllers/ElbowExampleController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
        state_interfaces:
          robot_state

      gravity_compensation_example_controller:
        type: franka_example_controllers/GravityCompensationExampleController

      gripper_example_controller:
        type: franka_example_controllers/GripperExampleController

      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController

      joint_impedance_with_ik_example_controller:
        type: franka_example_controllers/JointImpedanceWithIKExampleController

      joint_position_example_controller:
        type: franka_example_controllers/JointPositionExampleController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_velocity_example_controller:
        type: franka_example_controllers/JointVelocityExampleController

      model_example_controller:
        type: franka_example_controllers/ModelExampleController

      move_to_start_example_controller:
        type: franka_example_controllers/MoveToStartExampleController

      joint_position_adaptable_controller:
        type: franka_adaptable_controllers/JointPositionAdaptableController

      franka_joint_trajectory_controller:
        type: franka_joint_trajectory_controller/FrankaJointTrajectoryController

/**:
  joint_position_adaptable_controller:
    ros__parameters:
      is_target_relative: true
      use_target_directly: false
      control_joint_position: true

/**:
  cartesian_elbow_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_orientation_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_pose_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  cartesian_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"   

/**:
  elbow_example_controller:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: true #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: false # return update OK, although lock fails (no update occurs)

/**:
  gravity_compensation_example_controller:
    ros__parameters:
      arm_id: "fr3"
      
/**:
  joint_impedance_example_controller:
    ros__parameters:
      arm_id: "fr3"    
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

/**:
  joint_impedance_with_ik_example_controller:
    ros__parameters:
      arm_id: "fr3"
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

/**:
  joint_position_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  joint_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  joint_velocity_example_controller:
    ros__parameters:
      arm_id: "fr3"
 
/**:
  model_example_controller:
    ros__parameters:
      arm_id: "fr3"

/**:
  move_to_start_example_controller:
    ros__parameters:
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

/**:
  franka_joint_trajectory_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      command_interfaces:
        - effort

      state_interfaces:
        - position
        - velocity

      gains:
        fr3_joint1: {angle_wraparound: false, d: 2.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 24.0}
        fr3_joint2: {angle_wraparound: false, d: 2.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 24.0}
        fr3_joint3: {angle_wraparound: false, d: 2.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 24.0}
        fr3_joint4: {angle_wraparound: false, d: 1.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 24.0}
        fr3_joint5: {angle_wraparound: false, d: 1.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 10.0}
        fr3_joint6: {angle_wraparound: false, d: 1.0, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 6.0}
        fr3_joint7: {angle_wraparound: false, d: 0.5, ff_velocity_scale: 0.001, i: 0.0, i_clamp: 0.0, normalize_error: false, p: 2.0}

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      allow_integration_in_goal_trajectories: false
      allow_nonzero_velocity_at_trajectory_end: true
      open_loop_control: false
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0
