# Top-level dynamic launch configuration
# Defines which robots to spawn and overrides for namespace, ip, etc.
# The 'robot_config' field points to the specific yaml file in franka_robot_description/config/

franka_left:
  robot_config: "dfki_fr3_left"
  namespace: "franka_left"
  robot_ip: "192.168.1.4"
  use_fake_hardware: "false"
  end_effector_frame: "franka_left_fr3_link8"

franka_right:
  robot_config: "dfki_fr3_right"
  namespace: "franka_right"
  robot_ip: "192.168.0.2"
  use_fake_hardware: "false"
  end_effector_frame: "franka_right_rh_p12_rn_base"
