# Top-level dynamic launch configuration
# Defines which robots to spawn and overrides for namespace, ip, etc.
# The 'robot_config' field points to the specific yaml file in franka_robot_description/config/

franka_left:
  arm_id: "fr3"
  robot_config: "dfki_fr3_left"
  namespace: "franka_left"
  robot_ip: "192.168.1.4"
  use_fake_hardware: "false"
  end_effector_frame: "franka_left_grasp_point"
  urdf_description: "main_assemblies/bimanual_dfki.urdf.xacro"
  init_joint_position: [-0.5, 0.0, 0.0, -1.507, 0.0, 1.507, -0.5]

franka_right:
  arm_id: "fr3"
  robot_config: "dfki_fr3_right"
  namespace: "franka_right"
  robot_ip: "192.168.0.2"
  use_fake_hardware: "false"
  end_effector_frame: "franka_right_grasp_point"
  urdf_description: "main_assemblies/bimanual_dfki.urdf.xacro"
  init_joint_position: [0.5, 0.0, 0.0, -1.507, 0.0, 1.507, 0.5]
