# Configuration file for example.launch.py
# Defines parameters for launching 0 to many (here only 1 is enabled)
# Franka Robotics components in
# namespaced or non-namespaced environments.
#
# Note: This is a launch configuration file, not a node parameter file (see: controllers.yaml).
# Ensure all boolean values are quoted ("true" or "false") to avoid YAML parsing issues.
# Not all parameters are currently used but are included for future compatibility.
# Ensure each robot has a unique namespace to prevent topic conflicts.

# # franka example
# franka_example: # Arbitrary identifier for the first robot (a Mnemonic) 
#   arm_id: "fr3" # Reserved for future use, unique arm (i.e. robot model) identifier
#   arm_prefix: "franka_main" # Reserved for future use (e.g., robot unique prefix)
#   fake_sensor_commands: "false" # Enable fake sensor commands for simulation
#   joint_state_rate: 100 # Publishing rate for joint states (Hz)
#   load_gripper: "false" # Enable Franka Gripper ("true" or "false")
#   namespace: "franka_main" # Namespace for robot, any string (empty string allowed - meaningful names recommended)
#   robot_ip: "172.16.0.2" # Robot’s IP address or hostname
#   urdf_file: "fr3/fr3.urdf.xacro" # Relative path to URDF in franka_description/robots
#   use_fake_hardware: "false" # Use simulated hardware ("true" or "false")
#   use_rviz: "true" # Launch RViz if "true" (single instance for all namespaces)
#   xyz: "0 0 0"
#   rpy: "0 0 0"

# franka for single arm setup
franka_main:
  arm_id: "fr3"
  arm_prefix: "franka_main"
  fake_sensor_commands: "false"
  joint_state_rate: 100
  load_gripper: "false"
  namespace: "franka_main"
  robot_ip: "172.16.0.2"
  urdf_file: "fr3/fr3.urdf.xacro"
  srdf_file: "fr3/fr3.srdf.xacro"
  use_fake_hardware: "false"
  use_rviz: "false"
  xyz: "0 0 0"
  rpy: "0 0 0"
  init_joint_position: [0.0, -0.785, 0.0, -2.356, 0.0, 1.570, 0.785]

# left franka for dual arm setup
franka_left:
  arm_id: "fr3"
  arm_prefix: "franka_left"
  fake_sensor_commands: "false"
  joint_state_rate: 100
  load_gripper: "false"
  namespace: "franka_left"
  robot_ip: "192.168.0.4"
  urdf_file: "fr3/fr3.urdf.xacro"
  srdf_file: "fr3/fr3.srdf.xacro"
  use_fake_hardware: "false"
  use_rviz: "true"
  xyz: "-0.06 0.585 0"
  rpy: "0 0 0"
  init_joint_position: [-0.5, 0.0, -0.2, -1.3, 0.0, 1.8, 0.8]

# right franka for dual arm setup
franka_right:
  arm_id: "fr3"
  arm_prefix: "franka_right"
  fake_sensor_commands: "false"
  joint_state_rate: 100 
  load_gripper: "false"
  namespace: "franka_right"
  robot_ip: "192.168.1.2"
  urdf_file: "fr3/fr3.urdf.xacro"
  srdf_file: "fr3/fr3.srdf.xacro"
  use_fake_hardware: "false"
  use_rviz: "false" 
  xyz: "-0.06 -0.585 0"
  rpy: "0 0 0"
  init_joint_position: [0.5, 0.0, -0.2, -1.3, 0.0, 1.8, 0.2]
