zed_rig_aggregator:
  ros__parameters:  # important for ros2 reading via --ros-args --params-file
    camera_names: ["zed_middle", "zed_right", "zed_right_arm"]   
    rgb_topics:
      - "/zed_multi/zed_middle/rgb/color/rect/image"
      - "/zed_multi/zed_right/rgb/color/rect/image"
      - "/zed_multi/zed_right_arm/rgb/color/rect/image"
    depth_topics:
      - "/zed_multi/zed_middle/depth/depth_registered"
      - "/zed_multi/zed_right/depth/depth_registered"
      - "/zed_multi/zed_right_arm/depth/depth_registered"
    camera_info_topics:
      - "/zed_multi/zed_middle/depth/camera_info"
      - "/zed_multi/zed_right/depth/camera_info"
      - "/zed_multi/zed_right_arm/depth/camera_info"
    publish_topic: "/zed_rig/synced_raw_snapshot"
