node_name: "robi_client"
frequency: 30.0 # Hz
  
actions:
  - type: "DeltaJoint"
    start_idx: 0
    end_idx: 7
    topic: "/franka_right/policy_target_dq"
    msgtype: sensor_msgs/msg/JointState
    joint_names: [
      "franka_right_fr3_joint1", 
      "franka_right_fr3_joint2", 
      "franka_right_fr3_joint3", 
      "franka_right_fr3_joint4", 
      "franka_right_fr3_joint5", 
      "franka_right_fr3_joint6", 
      "franka_right_fr3_joint7"
    ]
  - type: "GripperAbsolute"
    start_idx: 7
    end_idx: 8
    topic: "/franka_right/gripper/gripper_controller/joint_trajectory"
    msgtype: "trajectory_msgs/msg/JointTrajectory"
    scale_factor: 1.1
    joint_names: ["franka_right_rh_r1"]

home_pose:
  topic: "/franka_right/target_pose"
  frame_id: "world"
  position: [0.3, -0.3, 0.4]  # x, y, z
  orientation: [0.95, 0.32, 0.0, 0.0]  # x, y, z, w (or however your C++ node expects it)
  gripper_topic: "/franka_right/gripper/gripper_controller/joint_trajectory"
  gripper_joint_name: "franka_right_rh_r1"
  gripper_open_val: 0.0

dataset:
  repo_id: "pick_and_place_delta_joint"
  root: /home/csil/projects/bimanual/data/pick_and_place_duplo/pick_and_place_delta_joint_20260412_130934
  episode: 0

server_address: "127.0.0.1:8080"