node_name: "robi_client"
frequency: 30.0 # Hz

mappings:
  "observation.state":
    - topic: "/franka_right/franka/joint_states"
      msgtype: "sensor_msgs/msg/JointState"
      fields: ["position", "velocity"]
      n_dof: 7
    - topic: "/franka_right/franka_gripper/joint_states"
      msgtype: sensor_msgs/msg/JointState
      fields: ["position"]
      n_dof: 1
  "observation.images.image":
    topic: "/zed_rig/synced_raw_snapshot"
    msgtype: "custom_interfaces/msg/RigSnapshot"
    camera_name: zed_right
    resize: [224, 224]
    center_crop: True
    encoding: rgb8
  "observation.images.image2":
    topic: "/zed_rig/synced_raw_snapshot"
    msgtype: "custom_interfaces/msg/RigSnapshot"
    camera_name: zed_right_arm
    resize: [224, 224]
    center_crop: True
    encoding: rgb8
  # "action":
  #   - topic: "/franka_right/fijk_debug"
  #     msgtype: franka_custom_msgs/msg/FIJKDebug
  #     fields: ["dq_commanded"]  # ["q_target", "dq_commanded", "q_target"]
  #   - topic: "/franka_right/gripper/gripper_controller/joint_trajectory"
  #     msgtype: trajectory_msgs/msg/JointTrajectory
  #     fields: ["position"]
  #     n_dof: 1
  #     point_index: 0
  
actions:
  - type: "DeltaJoint"
    start_idx: 0
    end_idx: 7
    topic: "/franka_right/target_dq"
    msgtype: sensor_msgs/msg/JointState
    joint_names: [
      "franka_right_fr3_joint1", 
      "franka_right_fr3_joint2", 
      "franka_right_fr3_joint3", 
      "franka_right_fr3_joint4", 
      "franka_right_fr3_joint5", 
      "franka_right_fr3_joint6", 
      "franka_right_fr3_joint7"
    ]
  - type: "GripperAbsolute"
    start_idx: 7
    end_idx: 8
    topic: "/franka_right/gripper/gripper_controller/joint_trajectory"
    msgtype: "trajectory_msgs/msg/JointTrajectory"
    scale_factor: 1.1
    joint_names: ["franka_right_rh_r1"]

home_pose:
  topic: "/franka_right/target_pose"
  frame_id: "world"
  position: [0.3, -0.3, 0.4]  # x, y, z
  orientation: [0.95, 0.32, 0.0, 0.0]  # x, y, z, w (or however your C++ node expects it)
  gripper_topic: "/franka_right/gripper/gripper_controller/joint_trajectory"
  gripper_joint_name: "franka_right_rh_r1"
  gripper_open_val: 0.0

policy:
  chunk_size_threshold: 0.7
  policy_type: "xvla" # beast_f, xvla
  pretrained_name_or_path: "/home/csil/projects/bimanual/policy_server/policy_ckpts/xvla_pick_and_place_duplo_delta_joint_20ep_30hz_2026-04-12_07-31-33/checkpoints/last/pretrained_model"
  # pretrained_name_or_path: "/home/csil/projects/bimanual/policy_server/policy_ckpts/beastf_pick_and_place_duplo_delta_joint_20ep_30hz_2026-04-11_20-50-38/checkpoints/last/pretrained_model"
  actions_per_chunk: 32
  policy_device: "cuda:0"
  task: "Pick and Place"

server_address: "127.0.0.1:8080"